// <auto-generated />
using System;
using Diary.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Diary.Web.Migrations
{
    [DbContext(typeof(DiaryDbContext))]
    [Migration("20210206135825_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Diary.Lib.Entry.Entry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EntryItems");
                });

            modelBuilder.Entity("Diary.Lib.UndoAction.UndoAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("ChangedId")
                        .HasColumnType("int");

                    b.Property<int>("GetUndoActionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChangedId");

                    b.ToTable("UndoActionItems");
                });

            modelBuilder.Entity("Diary.Lib.UndoAction.UndoAction", b =>
                {
                    b.HasOne("Diary.Lib.Entry.Entry", "Changed")
                        .WithMany()
                        .HasForeignKey("ChangedId");

                    b.Navigation("Changed");
                });
#pragma warning restore 612, 618
        }
    }
}
